### ISSUE TITLE
`isFunctionIsland` test when already JSX transformed (and a couple of other tiny issues)

### ISSUE THREAD

**Issue by coxmi** [dumbjs/preland#1]
Hello,

First of all, thanks for this! It's great to see smaller tools separate from monolithic frameworks.

I'm trying to use this in rollup/vite's transform step, which has already gone through the jsx-runtime transform. Do you think it's worth adding a condition in `isFunctionIsland` to handle `_jsxs` and `_jsx` function calls in the return statement? That way, it doesn't need to take over the full parsing from source.

Example pre-transformed source example:

```js
_jsxs(Breadcrumbs, {
  children: [
    _jsx(BreadcrumbLink, {
      href: "/link-01",
      children: "One"
    }), _jsx(BreadcrumbLink, {
      href: "/link-02",
      children: "Two"
    }), _jsx(BreadcrumbLink, {
      href: "/link-03",
      children: "Three"
  })]
})
```

Also, just a few tiny issues I've noticed: 

- Looks like it just bundles index.js, so ./ast isn't in the output — I get a `Missing "./ast" specifier in "@dumbjs/preland" package` error when trying to `import { astFromCode } from '@dumbjs/preland/ast'`

- readFile is not imported from node:fs, so it fails in `readSourceFile` here:
https://github.com/dumbjs/preland/blob/main/src/index.js#L9C18-L9C26

**Comment by barelyhuman** [comment]
I might've missed it while porting it from the original project i wrote it in. let me fix that for you. 


Support for pre-compiled Jsx is something i'm working with, current blocker is that in a bundled app, it might be hard to keep track of scope of what all needs to be a part of the island. 

if it's just the check you need working, that can be added 😊

**Comment by coxmi** [comment]
This does the trick in `isFunctionIsland` and more generally the setup seems to work well with a number of rough test components I've implemented so far 🤞

```js
const hasReturnRuntimeJSXTransformed = (
  	hasReturn.argument.type === 'CallExpression' && 
  	['_jsx', '_jsxs'].includes(hasReturn.argument.callee.name)
  )

  const hasReturnJSX = ['JSXFragment', 'JSXElement'].includes(hasReturn.argument.type)

  if (!(hasReturnJSX || hasReturnRuntimeJSXTransformed)) {
    return false
  }
```

After the island detection, I'm hoping the bundler sorts out all of the tree-shaking. I've had a go at pulling all your island detection and transpilation into a test repo, mainly to try out a few output options (per-route, atomic, global) and with a few changes to the client init code I think it could work quite well 🙂

**Comment by coxmi** [comment]
(I'm also just playing around really at the moment, so no worries about fixing stuff up just for me!)

**Comment by barelyhuman** [comment]
Could you try to install `@dumbjs/preland@beta` and see if the exports are causing an issue there as well? 

I have re-packaged with the missing import but the package has the required `exports` so it should be importable. 

also validate that the installed version is `0.0.0-beta.3`

**Comment by barelyhuman** [comment]
> (I'm also just playing around really at the moment, so no worries about fixing stuff up just for me!)

That's cool, it's a good idea to be able to parse compiled values and it's not that hard since it's mostly just nested function calls. Give me a day, I'll move in all the test cases and everything from the repo that I'm writing all of this in and we should have more stable packages as compared to what we have right now

**Comment by barelyhuman** [comment]
> After the island detection, I'm hoping the bundler sorts out all of the tree-shaking. I've had a go at pulling all your island detection and transpilation into a test repo, mainly to try out a few output options (per-route, atomic, global) and with a few changes to the client init code I think it could work quite well

That's cool, I have a per route bundler plugin in https://github.com/barelyhuman/preact-island-plugins, but those are more focused towards bundlers and I'm not _that_ happy with the API of that package though. 

unfortunately `sucrase` doesn't do bundling but we can have preset plugins with esbuild/vite/rollup to handle each scenario. 

Could be a complementary package of the same if needed 


> This does the trick in isFunctionIsland and more generally the setup seems to work well with a number of rough test components I've implemented so far 🤞

I shall add that :) , we also need to be able to handle the `h` style transforms that are done with the jsx runtime `classic` , and a `@pragma` or `@jsx` test and that should make it a complete check

**Comment by coxmi** [comment]
> Could you try to install @dumbjs/preland@beta and see if the exports are causing an issue there as well?

Yep that works great — package.json says "^0.0.0-beta.3"

> Give me a day, I'll move in all the test cases and everything from the repo that I'm writing all of this in and we should have more stable packages as compared to what we have right now

Awesome thank you!

> That's cool, I have a per route bundler plugin in https://github.com/barelyhuman/preact-island-plugins, but those are more focused towards bundlers and I'm not that happy with the API of that package though.

I gave that a go earlier this week with esbuild, but then faced a load of problems with esbuild anyway (asset paths between client/ssr, and preact appearing in each component bundle). Nothing is ever easy with bundlers... 

Anyway, thanks for building this stuff. Modern web dev is annoyingly next/react/astro focused right now, and it's great to see smaller tools for preact that keep the page load small 🙂

**Comment by barelyhuman** [comment]
> I gave that a go earlier this week with esbuild, but then faced a load of problems with esbuild anyway (asset paths between client/ssr, and preact appearing in each component bundle). Nothing is ever easy with bundlers...

Understandable , You can use this as a reference to get it working with esbuild, https://github.com/barelyhuman/nomen/blob/e73c177c9022c3ee08c0a9e11403df53fde5fcff/src/preact/module.js

**Comment by barelyhuman** [comment]
> Anyway, thanks for building this stuff. Modern web dev is annoyingly next/react/astro focused right now, and it's great to see smaller tools for preact that keep the page load small 🙂

I'm glad you like it :D
